### ISSUE TITLE
files from the config don't exist

### ISSUE THREAD

**Issue by GildedHonour** [holochain/holochain-basic-chat#22]
In conductor-config.toml:

1) `keystore_file = "./keystore.key"` ---> it doesn't exist.

2) `file = "holo-chat.dna.json"` ---> it doesn't exist.

What do they have to look like? How are they created initially: manually or generated?

**Comment by philipbeadle** [comment]
You create your own keys as explained in the readme. The json file is either built by you or you use the released version also explained in the readme.
