### ISSUE TITLE
what is supposed to happen?

### ISSUE THREAD

**Issue by hoijui** [holochain/holochain-basic-chat#46]
I am new to holochain, and just managed to run this app (I think?). it start sand then .. seems to be loading or something but... really, I don't knpw what is happening, if this is normal or a problem, if I am missing n3h or now, and if I will see other users in the end if I just start it, or if I have to somehow fetch an index or....
I wanted to use this app as a hello-world of holochain apps, to see something real, happening, and feel inspired. I am not sure if this can act like this, but It seemed the most likely candidate to me, and I am somewhat disillusioned/demotivated, after having gone through installing everything.
Just to give a newbs perspective, which I think is important to find new contributers, if not for more.
All the best and keep it up!

**Comment by hoijui** [comment]
.. no explanation at all, what is meant to happen, or what I woudl have to do to see other users?

**Comment by philipbeadle** [comment]
This will be included in Holoscape soon. Currently requires a bit of fiddly setup.
