### ISSUE TITLE
issue where clicking the channel name will cause agent to join the channel repeatedly

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-basic-chat#51]

**Comment by Connoropolous** [comment]
thanks for working on this @philipbeadle

**Comment by philipbeadle** [comment]
This is due to the links now being unique, so we're either going to have to check if the agent is in the room or add a new link type.

**Comment by philipbeadle** [comment]
Checks to see if youre in the room first now.
pub fn handle_join_stream(stream_address: Address) -> ZomeApiResult<()> {
    let mut all_member_ids = hdk::get_links(&stream_address, LinkMatch::Exactly("has_member"), LinkMatch::Any)?.addresses().to_owned();
    let mut join_room = true;
    while let Some(member_id) = all_member_ids.pop() {
        if &AGENT_ADDRESS.to_string() == &member_id.to_string() {
            hdk::debug(format!("No need to rejoin roomMessages: {:?}", &member_id.to_string())).ok();
            join_room = false;
        }
    }
    if join_room {
        hdk::utils::link_entries_bidir(&AGENT_ADDRESS, &stream_address, "member_of", "has_member", "", "")?;
        notify_room(stream_address, "new_room_member".to_string())?;
    }
    Ok(())
}
